//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.Etl.Runtime.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidSoft.Etl.Runtime.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[AllDataTypesTable]&apos;) AND type in (N&apos;U&apos;))
        ///DROP TABLE [dbo].[AllDataTypesTable]
        ///
        ///GO
        ///
        ///CREATE TABLE [dbo].[AllDataTypesTable]
        ///(
        ///	[Id] uniqueidentifier PRIMARY KEY NOT NULL,
        ///	[Null] nvarchar(255) NULL,
        ///	[Boolean] bit NULL,
        ///	[Byte] tinyint NULL,
        ///	[DateTime] datetime NULL,
        ///	[Decimal] numeric(29) NULL,
        ///	[Double] float NULL,
        ///	[Guid] uniqueidentifier,
        ///	[Int16] smallint NULL,
        ///	[Int32] int NULL,
        ///	[Int64] bigint NULL,
        ///	[Single]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllDataTypesTable {
            get {
                return ResourceManager.GetString("AllDataTypesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH t AS
        ///(
        ///	select newid() [Id], 1 n, &apos;:A&apos; suffix union all
        ///	select newid() [Id], 2 n, &apos;:B&apos; suffix union all
        ///	select newid() [Id], 3 n, &apos;:A&apos; suffix union all
        ///	select newid() [Id], 4 n, &apos;:B&apos; suffix union all
        ///	select newid() [Id], 5 n, &apos;:A&apos; suffix union all
        ///	select newid() [Id], 6 n, &apos;:B&apos; suffix union all
        ///	select newid() [Id], 7 n, &apos;:A&apos; suffix union all
        ///	select newid() [Id], 8 n, &apos;:B&apos; suffix union all
        ///	select newid() [Id], 9 n, &apos;:A&apos; suffix union all
        ///	select newid() [Id], 10 n, &apos;:B&apos; suffix
        ///)
        ///INSE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllDataTypesTableData {
            get {
                return ResourceManager.GetString("AllDataTypesTableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[CopyAllDataTypesTable]&apos;) AND type in (N&apos;P&apos;))
        ///DROP PROCEDURE [dbo].[CopyAllDataTypesTable]
        ///
        ///GO
        ///
        ///CREATE PROCEDURE [dbo].[CopyAllDataTypesTable]
        ///(
        ///	@etlPackageId uniqueidentifier,
        ///	@etlSessionId uniqueidentifier
        ///)
        ///AS
        ///BEGIN
        ///
        ///insert into [dbo].[AllDataTypesTableCopy]
        ///(
        ///	[Id],
        ///	[Null],
        ///	[Boolean],
        ///	[Byte],
        ///	[DateTime],
        ///	[Decimal],
        ///	[Double],
        ///	[Guid],
        ///	[Int16],
        ///	[Int32],
        ///	[Int64],
        ///	[Single],
        ///	[String],
        ///	[EtlPacka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopyAllDataTypesTable {
            get {
                return ResourceManager.GetString("CopyAllDataTypesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [EtlPackages]
        ///           ([Id]
        ///           ,[Name]
        ///           ,[Enabled]
        ///            )
        ///     VALUES
        ///           (&apos;0A82A1F6-748F-4725-88CB-22006E4E13BE&apos;
        ///            ,&apos;test_package&apos;
        ///            ,1
        ///           )
        ///
        ///INSERT INTO [EtlSessions]
        ///           ([EtlPackageId]
        ///           ,[EtlSessionId]
        ///           ,[StartDateTime]
        ///           ,[StartUtcDateTime]
        ///           ,[EndDateTime]
        ///           ,[EndUtcDateTime]
        ///           ,[Status]
        ///           ,[StartMessage]
        ///           ,[EndMessage])
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EtlTablesData {
            get {
                return ResourceManager.GetString("EtlTablesData", resourceCulture);
            }
        }
    }
}
