//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidSoft.Etl.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidSoft.Etl.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign value to bound variable &quot;{0}&quot;.
        /// </summary>
        internal static string CannotAssignBoundVariable {
            get {
                return ResourceManager.GetString("CannotAssignBoundVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign value to input variable &quot;{0}&quot; twice.
        /// </summary>
        internal static string CannotAssignInputVariable {
            get {
                return ResourceManager.GetString("CannotAssignInputVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size must be 1 or more.
        /// </summary>
        internal static string CsvReaderBufferSizeTooSmall {
            get {
                return ResourceManager.GetString("CsvReaderBufferSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to type &quot;{0}&quot;.
        /// </summary>
        internal static string CsvReaderCannotConvertValue {
            get {
                return ResourceManager.GetString("CsvReaderCannotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move to a previous record in forward-only mode.
        /// </summary>
        internal static string CsvReaderCannotMovePreviousRecordInForwardOnly {
            get {
                return ResourceManager.GetString("CsvReaderCannotMovePreviousRecordInForwardOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read record at index &quot;{0}&quot;.
        /// </summary>
        internal static string CsvReaderCannotReadRecordAtIndex {
            get {
                return ResourceManager.GetString("CsvReaderCannotReadRecordAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is invalid when the reader is closed.
        /// </summary>
        internal static string CsvReaderClosed {
            get {
                return ResourceManager.GetString("CsvReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has either not started or has already finished.
        /// </summary>
        internal static string CsvReaderEnumerationFinishedOrNotStarted {
            get {
                return ResourceManager.GetString("CsvReaderEnumerationFinishedOrNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was modified; enumeration operation may not execute.
        /// </summary>
        internal static string CsvReaderEnumerationVersionCheckFailed {
            get {
                return ResourceManager.GetString("CsvReaderEnumerationVersionCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with index &quot;{0}&quot; not found.
        /// </summary>
        internal static string CsvReaderFieldIndexNotFound {
            get {
                return ResourceManager.GetString("CsvReaderFieldIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSV appears to be corrupt near record &quot;{0}&quot; field &quot;{1}&quot; at position {2}. Current raw data : &quot;{3}&quot;.
        /// </summary>
        internal static string CsvReaderMalformedCsvException {
            get {
                return ResourceManager.GetString("CsvReaderMalformedCsvException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a supported missing field action.
        /// </summary>
        internal static string CsvReaderMissingFieldActionNotSupported {
            get {
                return ResourceManager.GetString("CsvReaderMissingFieldActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current record.
        /// </summary>
        internal static string CsvReaderNoCurrentRecord {
            get {
                return ResourceManager.GetString("CsvReaderNoCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file does not have headers.
        /// </summary>
        internal static string CsvReaderNoHeaders {
            get {
                return ResourceManager.GetString("CsvReaderNoHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of fields in the record is greater than the available space from index to the end of the destination array.
        /// </summary>
        internal static string CsvReaderNotEnoughSpaceInArray {
            get {
                return ResourceManager.GetString("CsvReaderNotEnoughSpaceInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid ParseErrorAction while inside a ParseError event.
        /// </summary>
        internal static string CsvReaderParseErrorActionInvalidInsideParseErrorEvent {
            get {
                return ResourceManager.GetString("CsvReaderParseErrorActionInvalidInsideParseErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a supported ParseErrorAction.
        /// </summary>
        internal static string CsvReaderParseErrorActionNotSupported {
            get {
                return ResourceManager.GetString("CsvReaderParseErrorActionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record index must be 0 or more.
        /// </summary>
        internal static string CsvReaderRecordIndexLessThanZero {
            get {
                return ResourceManager.GetString("CsvReaderRecordIndexLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; with value &quot;{1}&quot; cannot be converted to type &quot;{2}&quot;.
        /// </summary>
        internal static string FieldCannotBeConverted {
            get {
                return ResourceManager.GetString("FieldCannotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; field header not found.
        /// </summary>
        internal static string FieldHeaderNotFound {
            get {
                return ResourceManager.GetString("FieldHeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field index must be included in [0, FieldCount[. Specified field index was : &apos;{0}&apos;.
        /// </summary>
        internal static string FieldIndexOutOfRange {
            get {
                return ResourceManager.GetString("FieldIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; was not found.
        /// </summary>
        internal static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with index &quot;{0}&quot; has no mapping.
        /// </summary>
        internal static string FieldNotMapped {
            get {
                return ResourceManager.GetString("FieldNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type &quot;{1}&quot; in assembly &quot;{0}&quot;.
        /// </summary>
        internal static string InvokeMethodCannotFindType {
            get {
                return ResourceManager.GetString("InvokeMethodCannotFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke non-static method &quot;{1}.{2}&quot; from assembly &quot;{0}&quot;.
        /// </summary>
        internal static string InvokeMethodCannotInvokeNonStaticMethod {
            get {
                return ResourceManager.GetString("InvokeMethodCannotInvokeNonStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null or empty.
        /// </summary>
        internal static string PropertyCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} too long. Maximum length is {1}.
        /// </summary>
        internal static string PropertyTooLong {
            get {
                return ResourceManager.GetString("PropertyTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session &quot;{2}&quot; finished with status &quot;{3}&quot;.
        /// </summary>
        internal static string SessionFinished {
            get {
                return ResourceManager.GetString("SessionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session &quot;{2}&quot; started.
        /// </summary>
        internal static string SessionStarted {
            get {
                return ResourceManager.GetString("SessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &quot;{0}&quot; finished with status &quot;{1}&quot;.
        /// </summary>
        internal static string StepFinished {
            get {
                return ResourceManager.GetString("StepFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step &quot;{0}&quot; started.
        /// </summary>
        internal static string StepStarted {
            get {
                return ResourceManager.GetString("StepStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown trim option &quot;{0}&quot;.
        /// </summary>
        internal static string UnknownTrimOption {
            get {
                return ResourceManager.GetString("UnknownTrimOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; has unknown binding &quot;{1}&quot;.
        /// </summary>
        internal static string UnknownVariableBinding {
            get {
                return ResourceManager.GetString("UnknownVariableBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; has unknown modifier &quot;{1}&quot;.
        /// </summary>
        internal static string UnknownVariableModifier {
            get {
                return ResourceManager.GetString("UnknownVariableModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string ValidateCsvErrorColumnPrefix {
            get {
                return ResourceManager.GetString("ValidateCsvErrorColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ValidateCsvErrorLinePrefix {
            get {
                return ResourceManager.GetString("ValidateCsvErrorLinePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string ValidateCsvErrorPositionPrefix {
            get {
                return ResourceManager.GetString("ValidateCsvErrorPositionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while translation of field &quot;{0}&quot; with value &quot;{1}&quot;.
        /// </summary>
        internal static string ValueTranslationError {
            get {
                return ResourceManager.GetString("ValueTranslationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source field &quot;{0}&quot; was not found.
        /// </summary>
        internal static string ValueTranslationSourceFieldNotFound {
            get {
                return ResourceManager.GetString("ValueTranslationSourceFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is set to &quot;{1}&quot;.
        /// </summary>
        internal static string VariableInit {
            get {
                return ResourceManager.GetString("VariableInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name cannot be empty.
        /// </summary>
        internal static string VariableNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("VariableNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; not found.
        /// </summary>
        internal static string VariableNotFound {
            get {
                return ResourceManager.GetString("VariableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables initialized.
        /// </summary>
        internal static string VariablesInitFinished {
            get {
                return ResourceManager.GetString("VariablesInitFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing variables....
        /// </summary>
        internal static string VariablesInitStarted {
            get {
                return ResourceManager.GetString("VariablesInitStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables updated.
        /// </summary>
        internal static string VariablesUpdateFinished {
            get {
                return ResourceManager.GetString("VariablesUpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables was changed. Updating variables....
        /// </summary>
        internal static string VariablesUpdateStarted {
            get {
                return ResourceManager.GetString("VariablesUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable token at position {0} has no closing parent.
        /// </summary>
        internal static string VariableTokenHasNoClosingParenthese {
            get {
                return ResourceManager.GetString("VariableTokenHasNoClosingParenthese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &quot;{0}&quot; is set to &quot;{1}&quot;.
        /// </summary>
        internal static string VariableUpdate {
            get {
                return ResourceManager.GetString("VariableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to type &quot;{0}&quot;.
        /// </summary>
        internal static string XmlReaderCannotConvertValue {
            get {
                return ResourceManager.GetString("XmlReaderCannotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML element &quot;{0}&quot; was not found.
        /// </summary>
        internal static string XmlReaderElementNotFound {
            get {
                return ResourceManager.GetString("XmlReaderElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected closing tag for XML element &quot;{0}&quot; but found closing tag for element &quot;{1}&quot;.
        /// </summary>
        internal static string XmlReaderExpectedClosingTag {
            get {
                return ResourceManager.GetString("XmlReaderExpectedClosingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected XML element &quot;{0}&quot; but found element &quot;{1}&quot;.
        /// </summary>
        internal static string XmlReaderExpectedElement {
            get {
                return ResourceManager.GetString("XmlReaderExpectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with index &quot;{0}&quot; not found.
        /// </summary>
        internal static string XmlReaderFieldIndexNotFound {
            get {
                return ResourceManager.GetString("XmlReaderFieldIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; not found.
        /// </summary>
        internal static string XmlReaderFieldNameNotFound {
            get {
                return ResourceManager.GetString("XmlReaderFieldNameNotFound", resourceCulture);
            }
        }
    }
}
